name: BirthdayReminders
options:
  bundleIdPrefix: com
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.birthdayreminders
    INFOPLIST_FILE: BirthdayReminders/Info.plist
    CODE_SIGN_ENTITLEMENTS: BirthdayReminders/BirthdayReminders.entitlements
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1"
    GENERATE_INFOPLIST_FILE: false

targets:
  BirthdayReminders:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: BirthdayReminders
        excludes:
          - "**/*.entitlements"
          - "Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.birthdayreminders
        INFOPLIST_FILE: BirthdayReminders/Info.plist
        CODE_SIGN_ENTITLEMENTS: BirthdayReminders/BirthdayReminders.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: BirthdayReminders/BirthdayReminders.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.birthdayreminders
        com.apple.developer.default-data-protection: NSFileProtectionComplete
